# Generated by Django 4.2.1 on 2023-06-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default=None, max_length=70)),
                ('Last_Name', models.CharField(default=None, max_length=70)),
                ('User_Name', models.CharField(default=None, max_length=70)),
                ('Email', models.EmailField(default=None, max_length=70)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
